### ISSUE TITLE
cmd/govim: Vim sometimes freezes on triggering completion

### ISSUE THREAD

**Issue by hmarr** [myitcv/govim#157]
### What version of Vim/Gvim are you using?

<details><summary>Vim/Gvim version</summary><br><pre>
$ vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 11 2019 17:46:54)
macOS version
Included patches: 1-1150
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     -tag_old_static
+arabic            -farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    -tcl
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +textprop
+byte_offset       -hangul_input      +num64             +timers
+channel           +iconv             +packages          +title
+cindent           +insert_expand     +path_extra        -toolbar
-clientserver      +job               +perl              +user_commands
+clipboard         +jumplist          +persistent_undo   +vartabs
+cmdline_compl     +keymap            +postscript        +vertsplit
+cmdline_hist      +lambda            +printer           +virtualedit
+cmdline_info      +langmap           +profile           +visual
+comments          +libcall           -python            +visualextra
+conceal           +linebreak         +python3           +viminfo
+cryptv            +lispindent        +quickfix          +vreplace
+cscope            +listcmds          +reltime           +wildignore
+cursorbind        +localmap          +rightleft         +wildmenu
+cursorshape       +lua               +ruby              +windows
+dialog_con        +menu              +scrollbind        +writebackup
+diff              +mksession         +signs             -X11
+digraphs          +modify_fname      +smartindent       -xfontset
-dnd               +mouse             +startuptime       -xim
-ebcdic            -mouseshape        +statusline        -xpm
+emacs_tags        +mouse_dec         -sun_workshop      -xsmp
+eval              -mouse_gpm         +syntax            -xterm_clipboard
+ex_extra          -mouse_jsbterm     +tag_binary        -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -lintl -framework AppKit  -L/usr/local/opt/lua/lib -llua5.3 -mmacosx-version-min=10.14 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.28.1/lib/perl5/5.28.1/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3.7m -framework CoreFoundation  -lruby.2.6
</pre></details>

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.4 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/harry/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/harry"
GOPROXY=""
GORACE=""
GOROOT="/Users/harry/.asdf/installs/golang/1.12.4/go"
GOTMPDIR=""
GOTOOLDIR="/Users/harry/.asdf/installs/golang/1.12.4/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/harry/src/github.com/dependabot/update-job-runner/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/v3/ykhb4lxs601f4z4pnhcwps400000gp/T/go-build873443126=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What version/commit of `govim` are you using?

`86bdf03cca856cb6789ebb1a66fa4c44a2c08af5`

### How did you install `govim`?

vim-plug

### What did you do?

Triggered completion via `<c-x><c-o>`

### What did you expect to see?

The completion options appear.

### What did you see instead?

Vim hang for maybe 30 seconds or so, showing `-- Omni completion (^O^N^P) -- Searching...` in the status bar.

The full log output is [here](https://gist.githubusercontent.com/hmarr/afdcdf835b575aa1a143fbef48115247/raw/9fc8a8015b5895a3ae1493e56803d0008927b50e/govim.log) (the log file is too big for an issue or even viewing in the regular gist UI). You can see at the end, there's a ~30 gap where nothing happens. During that time vim was unresponsive (I suppose due to #99).

**Comment by myitcv** [comment]
Strange one. Because it appears from the `govim` logs that Vim is just doing nothing (see `019-04-19T06:54:09.811351` - the completion results have been sent to Vim).

I've just merged 8a9e8cab3c6c992f2cf781b5855b78c6011b6356 to always create a Vim channel log file. This will help confirm that Vim has received the message sent from `govim`. See https://github.com/myitcv/govim/wiki/Debugging-govim-plugin-failures for more details on log file creation.

Please can you upgrade to the latest `govim` and see if you can repro this? 

I also note you're using a version of Vim that is slightly behind the very aggressive demands of https://github.com/myitcv/govim/wiki/FAQ#what-versions-of-vim-and-go-are-supported-with-govim! Any chance you can upgrade to at least the minimum shown in https://github.com/myitcv/govim/blob/master/.travis.yml?

**Comment by hmarr** [comment]
I just got another one of these. Again, while editing a file I can't share unfortunately.

This time I don't think it was after triggering completion manually. I also spotted this in `:messages`:

```
Error detected while processing function <SNR>36_callbackAutoCommand:
line    4:
E605: Exception not caught: got error whilst handling autocommand:1: driver error: ChannelExpr("{\"Num\": bufnr(\"\"),
 \"Name\": expand('%:p'), \"Contents\": join(getline(0, \"$\"), \"\\n\")}") failed: failed to expr({"Num": bufnr(""),
"Name": expand('%:p'), "Contents": join(getline(0, "$"), "\n")}) in Vim: Caught 'Vim:Interrupt' in function <SNR>36_ca
llbackAutoCommand[2]..<SNR>36_define, line 48
```

Not sure if that's relevant.

Will keep adding any extra information I can gather along the way :-)

**Comment by hmarr** [comment]
I also just update govim, so will be able to post the channel logs next time.

**Comment by myitcv** [comment]
Per our offline exchange, I think you're currently running into a variant of https://github.com/golang/go/issues/31341. If you look at the bottom of the `govim` log you'll see something like:

```
2019-04-22T08:46:49.872631: gopls stderr: panic: runtime error: slice bounds out of range
2019-04-22T08:46:49.872650: gopls stderr:
2019-04-22T08:46:49.872659: gopls stderr: goroutine 3160 [running]:
2019-04-22T08:46:49.873354: gopls stderr: golang.org/x/tools/internal/span.ToUTF16Column(0xc, 0xa, 0x100, 0xc00008f600, 0x100, 0x100, 0xffffffffffffffff, 0xc, 0xa)
2019-04-22T08:46:49.873374: gopls stderr: 	/Users/someone/pkg/mod/golang.org/x/tools@v0.0.0-20190417223002-a5870b403859/internal/span/utf16.go:41 +0x57a
2019-04-22T08:46:49.873705: gopls stderr: golang.org/x/tools/internal/lsp/protocol.(*ColumnMapper).Position(0xc009583c20, 0xc, 0xa, 0x100, 0x0, 0x0, 0x13309ad, 0x13b87c0)
2019-04-22T08:46:49.873722: gopls stderr: 	/Users/someone/pkg/mod/golang.org/x/tools@v0.0.0-20190417223002-a5870b403859/internal/lsp/protocol/span.go:62 +0x63
2019-04-22T08:46:49.873734: gopls stderr: golang.org/x/tools/internal/lsp/protocol.(*ColumnMapper).Range(0xc009583c20, 0xc00823f8b0, 0x50, 0xc, 0xa, 0x100, 0xc, 0xa, 0x100, 0x0, ...)
2019-04-22T08:46:49.873765: gopls stderr: 	/Users/someone/pkg/mod/golang.org/x/tools@v0.0.0-20190417223002-a5870b403859/internal/lsp/protocol/span.go:50 +0x40c
2019-04-22T08:46:49.873798: gopls stderr: golang.org/x/tools/internal/lsp.toProtocolDiagnostics(0x14d22e0, 0xc007f120c0, 0x14d2460, 0xc00010e400, 0xc000188150, 0x1, 0x1, 0x1, 0x0, 0xc00231b3c8, ...)
2019-04-22T08:46:49.873812: gopls stderr: 	/Users/someone/pkg/mod/golang.org/x/tools@v0.0.0-20190417223002-a5870b403859/internal/lsp/diagnostics.go:85 +0x215
2019-04-22T08:46:49.873850: gopls stderr: golang.org/x/tools/internal/lsp.(*Server).publishDiagnostics(0xc0000da7e0, 0x14d22e0, 0xc007f120c0, 0xc00010e400, 0xc00823f860, 0x50, 0xc000188150, 0x1, 0x1, 0x0, ...)
2019-04-22T08:46:49.873872: gopls stderr: 	/Users/someone/pkg/mod/golang.org/x/tools@v0.0.0-20190417223002-a5870b403859/internal/lsp/diagnostics.go:60 +0x82
2019-04-22T08:46:49.873882: gopls stderr: golang.org/x/tools/internal/lsp.(*Server).cacheAndDiagnose.func1(0xc00010e400, 0xc0000da7e0, 0xc00d41f090, 0x50)
2019-04-22T08:46:49.873892: gopls stderr: 	/Users/someone/pkg/mod/golang.org/x/tools@v0.0.0-20190417223002-a5870b403859/internal/lsp/diagnostics.go:37 +0x356
2019-04-22T08:46:49.873899: gopls stderr: created by golang.org/x/tools/internal/lsp.(*Server).cacheAndDiagnose
2019-04-22T08:46:49.873907: gopls stderr: 	/Users/someone/pkg/mod/golang.org/x/tools@v0.0.0-20190417223002-a5870b403859/internal/lsp/diagnostics.go:21 +0x157
2019-04-22T08:46:49.960962: 
```

The `gopls` folks have included some mitigation code for this as of `golang.org/x/tools v0.0.0-20190422233926-fe54fb35175b`, but I'm seeing an off-by-one error in that. So I'll wait until we have a proper fix before moving forward.

So I'm going to mark this as a dup of #98. Please shout if you see any other completion-related bugs that warrant either reopening this issue or a new one.

Thanks again for the detail on all of this
