### ISSUE TITLE
cmd/govim: plugin died :(

### ISSUE THREAD

**Issue by leighmcculloch** [myitcv/govim#164]
### What version of Vim/Gvim are you using?

<details><summary>Vim/Gvim version</summary><br><pre>
$ vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 22 2019 12:55:04)
Included patches: 1-875, 878, 884, 948
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     +tag_old_static
+arabic            +farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    +tcl
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +textprop
+byte_offset       -hangul_input      +num64             +timers
+channel           +iconv             +packages          +title
+cindent           +insert_expand     +path_extra        -toolbar
-clientserver      +job               +perl              +user_commands
-clipboard         +jumplist          +persistent_undo   +vartabs
+cmdline_compl     +keymap            +postscript        +vertsplit
+cmdline_hist      +lambda            +printer           +virtualedit
+cmdline_info      +langmap           +profile           +visual
+comments          +libcall           -python            +visualextra
+conceal           +linebreak         +python3           +viminfo
+cryptv            +lispindent        +quickfix          +vreplace
+cscope            +listcmds          +reltime           +wildignore
+cursorbind        +localmap          +rightleft         +wildmenu
+cursorshape       +lua               +ruby              +windows
+dialog_con        +menu              +scrollbind        +writebackup
+diff              +mksession         +signs             -X11
+digraphs          +modify_fname      +smartindent       -xfontset
-dnd               +mouse             +startuptime       -xim
-ebcdic            -mouseshape        +statusline        -xpm
+emacs_tags        +mouse_dec         -sun_workshop      -xsmp
+eval              +mouse_gpm         +syntax            -xterm_clipboard
+ex_extra          -mouse_jsbterm     +tag_binary        -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-nWVbVg/vim-8.1.0875=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.28/CORE -lperl -ldl -lm -lpthread -lcrypt
 -L/usr/lib/python3.7/config-3.7m-x86_64-linux-gnu -lpython3.7m -lcrypt -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm -lruby-2.5 -lpthread -lgmp -ldl -lcrypt -lm
</pre></details>

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.4 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/home/leighmcculloch/local/bin"
GOCACHE="/home/leighmcculloch/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/leighmcculloch/go"
GOPROXY=""
GORACE=""
GOROOT="/home/leighmcculloch/local/bin/go"
GOTMPDIR=""
GOTOOLDIR="/home/leighmcculloch/local/bin/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/leighmcculloch/devel/braintree-go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build995624478=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What version/commit of `govim` are you using?

`v0.0.6`

### How did you install `govim`?

`vim-plug`
```vim
Plug 'myitcv/govim', { 'tag': 'v0.0.6' }
```

### What did you do?

Open vim with `vim`.

### What did you expect to see?

Opened vim without errors.

### What did you see instead?

```
Installing govim and gopls
Error detected while processing function <SNR>14_govimExit:
line   10:
E605: Exception not caught: govim plugin died :(
```

**Comment by myitcv** [comment]
Thanks for the report @leighmcculloch. Sorry for the failure :(

Please can you:

* try with https://github.com/myitcv/govim/releases/tag/v0.0.7 (just tagged) - this has extra logging on the Vim side which will be useful
* try and use a later Vim version https://github.com/myitcv/govim/wiki/FAQ#what-versions-of-vim-and-go-are-supported-with-govim

**Comment by leighmcculloch** [comment]
@myitcv No apologies! This is software, open, and clearly very new 🙂 and I was just giving it a first go. I realize it's not polished yet! A side note, I gave same version of `gopls` a go with `vim-lsp` and it appeared to work. I've contributed to `java-language-server` and `vim-lsp` a bit and am really interested to see where `govim` goes.

I've given it another go with the same `v0.0.6` and `vim` `master` branch, so as far as I know that's the latest version as it gets.

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 21 2019 20:42:51)
Included patches: 1-1198
Compiled by https://github.com/leighmcculloch/vim-compile install-debian.sh
Huge version without GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     -tag_old_static
+arabic            -farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    +tcl
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +textprop
+byte_offset       -hangul_input      +num64             +timers
+channel           +iconv             +packages          +title
+cindent           +insert_expand     +path_extra        -toolbar
-clientserver      +job               +perl              +user_commands
-clipboard         +jumplist          +persistent_undo   +vartabs
+cmdline_compl     +keymap            +postscript        +vertsplit
+cmdline_hist      +lambda            +printer           +virtualedit
+cmdline_info      +langmap           +profile           +visual
+comments          +libcall           -python            +visualextra
+conceal           +linebreak         +python3           +viminfo
+cryptv            +lispindent        +quickfix          +vreplace
+cscope            +listcmds          +reltime           +wildignore
+cursorbind        +localmap          +rightleft         +wildmenu
+cursorshape       +lua               +ruby              +windows
+dialog_con        +menu              +scrollbind        +writebackup
+diff              +mksession         +signs             -X11
+digraphs          +modify_fname      +smartindent       -xfontset
-dnd               +mouse             +startuptime       -xim
-ebcdic            -mouseshape        +statusline        -xpm
+emacs_tags        +mouse_dec         -sun_workshop      -xsmp
+eval              +mouse_gpm         +syntax            -xterm_clipboard
+ex_extra          -mouse_jsbterm     +tag_binary        -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/home/leighmcculloch/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E   -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.28/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.7/config-3.7m-x86_64-linux-gnu -lpython3.7m -lcrypt -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm -lruby-2.5 -lpthread -lgmp -ldl -lcrypt -lm     
```

The same error occurred with latest vim 👆 and `v0.0.6`.

I then updated to `v0.0.7` and this error log 👇 was generated to the vim channel file:

```
==== start log session ====
  0.184703 : Starting job: /home/leighmcculloch/devel/vim_dotfiles/plugged/govim/cmd/govim/.bin/8a9e8cab3c6c992f2cf781b5855b78c6011b6356/govim  /home/leighmcculloch/devel/vim_dotfiles/plugged/govim/cmd/govim/.bin/8a9e8cab3c6c992f2cf781b5855b78c6011b6356/gopls
  0.184731 on 0: Created channel
  0.199913 on 0: channel_select_check(): Read EOF from ch_part[1], closing
  0.199941 RECV on 0(err): 'executing job failed: No such file or directory'
  0.200261 on 0: channel_select_check(): Read EOF from ch_part[2], closing
  0.280835 : looking for messages on channels
  0.280851 on 0: Closing channel because all readable fds are closed
  0.280862 on 0: Closing channel
  0.280881 on 0: Job ended
  0.280889 on 0: Invoking exit callback <SNR>12_govimExit
  0.280917 : ERROR: Error detected while processing function <SNR>12_govimExit:
  0.280958 : ERROR: line   10:
  0.280977 : ERROR: E605: Exception not caught: govim plugin died :(
  1.285178 : looking for messages on channels
 10.458327 : Exiting...
```

**Comment by myitcv** [comment]
Please can you copy-paste the output from `:messages` in Vim, once it has loaded? That will hopefully give us some more clues as to why the install failed.

**Comment by myitcv** [comment]
@leighmcculloch when you get round to trying this again, if you could try with the latest release that would be appreciated.

**Comment by myitcv** [comment]
I'm going to close this for now, on the basis much has changed since the original report. Please do re-open or raise a new issue if you spot this issue again/anything else.

**Comment by leighmcculloch** [comment]
This is still happening with the latest version of `master`, b15ac0a.

Contents of `:messages`:

```
:messages
Messages maintainer: Bram Moolenaar <Bram@vim.org>
Installing govim and gopls
Error detected while processing function <SNR>45_govimExit:
line   10:
E605: Exception not caught: govim plugin died :(
```

Version of `vim` in use is compiled from todays vim `master` branch:

```
$ vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 12 2019 01:36:01)
Included patches: 1-1839
```

**Comment by myitcv** [comment]
@leighmcculloch - are you able to run the command `:GOVIMLogfilePaths`? If so, please can you include the output from the three log files listed (in a gist perhaps)?

**Comment by leighmcculloch** [comment]
This is the output I see.
```
:GOVIMLogfilePaths
Vim channel logfile: /tmp/vim_channel_log_20190812_0610_29_CPC3LxjGc1jY
govim logfile: <unset>
gopls logfile: <unset>
```
I looked through the wiki earlier to see how to set the other logfiles, but I couldn't see how. The contents of the first file is relatively short:
```
==== start log session ====
==== start log session ====
==== start log session ====
  1.906742 : Starting job: /home/leighmcculloch/devel/vim_dotfiles/plugged/govim/cmd/govim/.bin/b15ac0a948cb00443cc6d80c6dd2e96a485290bd/govim  /home/leighmcculloch/devel/vim_dotfiles/plugged/govim/cmd/govim/.bin/b15ac0a948cb00443cc6d80c6dd2e96a485290bd/gopls
  1.906862 on 0: Created channel
  1.938148 on 0: channel_select_check(): Read EOF from ch_part[1], closing
  1.938194 RECV on 0(err): 'executing job failed: No such file or directory
'
  1.946384 on 0: channel_select_check(): Read EOF from ch_part[2], closing
  2.048542 : looking for messages on channels
  2.048585 on 0: Closing channel because all readable fds are closed
  2.048594 on 0: Closing channel
  2.048628 : ERROR silent: E474: Invalid argument
  2.048636 ERR on 0: Decoding failed - discarding input
  2.048668 on 0: Job ended
  2.048684 on 0: Invoking exit callback <SNR>45_govimExit
  2.048739 : ERROR: Error detected while processing function <SNR>45_govimExit:
  2.048805 : ERROR: line   10:
  2.048849 : ERROR: E605: Exception not caught: govim plugin died :(
  3.055239 : looking for messages on channels
```

**Comment by myitcv** [comment]
Ok, that error message is now at least a tiny bit more useful :)

```
/home/leighmcculloch/devel/vim_dotfiles/plugged/govim/cmd/govim/.bin/b15ac0a948cb00443cc6d80c6dd2e96a485290bd/govim
/home/leighmcculloch/devel/vim_dotfiles/plugged/govim/cmd/govim/.bin/b15ac0a948cb00443cc6d80c6dd2e96a485290bd/gopls
```

Please can you see whether either of the above files exist? 

Does the path (i.e. all directories) to those files also exist?

**Comment by leighmcculloch** [comment]
`/home/leighmcculloch/devel/vim_dotfiles/plugged/govim/cmd/govim` exists and contains go files, but there is no `.bin` folder inside it.

What kicks off the building of the files into the `.bin` folder? It's worth mentioning I have a `GOBIN` defined as an environment variable so I see the `govim` binary in that folder.

**Comment by myitcv** [comment]
Sounds like we're getting closer...

The relevant code is here: https://github.com/myitcv/govim/blob/ecc1d8d0a71aafe7ade3c0f8462671515ce99297/plugin/govim.vim#L307-L333

I've just done a test on my setup with a `GOBIN` set to something else and I see `govim` and `gopls` being installed to the `.bin` directory. 

If you unset `GOBIN`, what happens?

**Comment by leighmcculloch** [comment]
I did `unset GOBIN` before running `vim` and same thing happened. I dropped some additional `echom`s inside that function and that was a little enlightening. The `system` function is returning an empty string and there is no shell error. It's like the call out to go install is doing nothing.

**Comment by leighmcculloch** [comment]
A little more fiddling, if I run the following command at the terminal I get an error:

```
$ GOBIN=$HOME/.vim/plugged/govim/cmd/govim/.bin/b15ac0a948cb00443cc6d80c6dd2e96a485290bd/ go install github.com/myitcv/govim/cmd/govim golang.org/x/tools/gopls 2>&1
can't load package: package github.com/myitcv/govim/cmd/govim: cannot find package "github.com/myitcv/govim/cmd/govim" in any of:
        /home/leighmcculloch/local/bin/go/1.13beta1/src/github.com/myitcv/govim/cmd/govim (from $GOROOT)
        /home/leighmcculloch/go/src/github.com/myitcv/govim/cmd/govim (from $GOPATH)
```

If I then run these commands, and then rerun the `go install` above, it works fine.
```
$ go get github.com/myitcv/govim/cmd/govim
$ go get golang.org/x/tools/gopls
```

`go install` won't download packages it will just compile them and I don't see `go get` occurring anywhere in the govim install process, so I think this is what's missing? Or is the assumption that we should install those tools separately?

**Comment by myitcv** [comment]
You will need to invoke that command from the correct directory, where the module is defined. 

What do you get with:

```
$ cd /home/leighmcculloch/devel/vim_dotfiles/plugged/govim
$ GO111MODULE=on GOBIN=$HOME/.vim/plugged/govim/cmd/govim/.bin/b15ac0a948cb00443cc6d80c6dd2e96a485290bd/ go install github.com/myitcv/govim/cmd/govim golang.org/x/tools/gopls
```

**Comment by leighmcculloch** [comment]
Ah. Running those two commands worked. 🤔 Downloaded all deps and installed the binaries in the right place.

**Comment by myitcv** [comment]
So then I think this points to the `system` call failing for some reason?

**Comment by leighmcculloch** [comment]
It would seem that the `system` call is doing nothing rather than strictly failing, because the value of `v:shell_error` is `0`.

I've inserted some alternative system calls ahead of the go install call like `go version` and even `which go` and all point to the correct go binary.

**Comment by leighmcculloch** [comment]
Okay, looks like `GOBIN` overriding the script is doing isn't taking hold.
https://github.com/myitcv/govim/blob/ecc1d8d0a71aafe7ade3c0f8462671515ce99297/plugin/govim.vim#L322

The system call is running with `GOBIN` still set to the value in my environment, so that's the reason `v:shell_error` is `0`, because the install is succeeding, it's just installing into my `GOBIN` instead of the `govim` `targetdir`.

**Comment by leighmcculloch** [comment]
@myitcv I've opened a fix #448 that I can confirm resolves the issue. I think the issue is that govim overrides GOBIN in VIM's shell, assuming when the `system` command runs that it's not in a new shell. My shell sets GOBIN so GOBIN is getting replaced again at that point.

**Comment by myitcv** [comment]
Ah, the bit I couldn't understand at all was just made clear by your commit message in #448 

> GOBIN is defined in my shell rc file so it's possible when system is running the command it's starting a new shell which is setting GOBIN again.

Thanks - will take a look at that PR.

**Comment by myitcv** [comment]
@leighmcculloch - thanks very much for your patience and debugging on this. But also the PR to fix things!
