### ISSUE TITLE
cmd/govim: output on every vim startup stating installing govim and gopls

### ISSUE THREAD

**Issue by leighmcculloch** [myitcv/govim#165]
### What version of Vim/Gvim are you using?

<details><summary>Vim/Gvim version</summary><br><pre>
$ vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 21 2019 20:42:51)
Included patches: 1-1198
Compiled by https://github.com/leighmcculloch/vim-compile install-debian.sh
Huge version without GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     -tag_old_static
+arabic            -farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    +tcl
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +textprop
+byte_offset       -hangul_input      +num64             +timers
+channel           +iconv             +packages          +title
+cindent           +insert_expand     +path_extra        -toolbar
-clientserver      +job               +perl              +user_commands
-clipboard         +jumplist          +persistent_undo   +vartabs
+cmdline_compl     +keymap            +postscript        +vertsplit
+cmdline_hist      +lambda            +printer           +virtualedit
+cmdline_info      +langmap           +profile           +visual
+comments          +libcall           -python            +visualextra
+conceal           +linebreak         +python3           +viminfo
+cryptv            +lispindent        +quickfix          +vreplace
+cscope            +listcmds          +reltime           +wildignore
+cursorbind        +localmap          +rightleft         +wildmenu
+cursorshape       +lua               +ruby              +windows
+dialog_con        +menu              +scrollbind        +writebackup
+diff              +mksession         +signs             -X11
+digraphs          +modify_fname      +smartindent       -xfontset
-dnd               +mouse             +startuptime       -xim
-ebcdic            -mouseshape        +statusline        -xpm
+emacs_tags        +mouse_dec         -sun_workshop      -xsmp
+eval              +mouse_gpm         +syntax            -xterm_clipboard
+ex_extra          -mouse_jsbterm     +tag_binary        -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/home/leighmcculloch/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E   -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.28/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.7/config-3.7m-x86_64-linux-gnu -lpython3.7m -lcrypt -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm -lruby-2.5 -lpthread -lgmp -ldl -lcrypt -lm     
</pre></details>

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.4 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN="/home/leighmcculloch/local/bin"
GOCACHE="/home/leighmcculloch/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/leighmcculloch/go"
GOPROXY=""
GORACE=""
GOROOT="/home/leighmcculloch/local/bin/go"
GOTMPDIR=""
GOTOOLDIR="/home/leighmcculloch/local/bin/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build721650229=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What version/commit of `govim` are you using?

```
v0.0.7
```

### How did you install `govim`?

```vimscript
Plug 'myitcv/govim', { 'tag': 'v0.0.7' }
```

### What did you do?

Opened vim.

### What did you expect to see?

Just vim open, nothing else. Only plugins relevant to the filetype I'm editing being triggered.

### What did you see instead?

The words below printed out, and a pause. This appears the first time when installing them, but also every time after that with a pause, even though they are installed. The text also appeared even if I'm not editing a Go file so it appears the plugin is being loaded and triggered when not working on Go files.

```
Installing govim and gopls
```

**Comment by myitcv** [comment]
Sounds like `govim` is not installing properly for some reason. 

Please can you copy-paste the output from `:messages` in Vim, once it has loaded? That will hopefully give us some more clues as to why the install failed.

**Comment by myitcv** [comment]
@leighmcculloch when you get round to trying this again, if you could try with the latest release that would be appreciated.

**Comment by myitcv** [comment]
I'm going to close this for now, on the basis much has changed since the original report. Please do re-open or raise a new issue if you spot this issue again/anything else.

**Comment by leighmcculloch** [comment]
This is still happening with the latest version of `master`, b15ac0a.

Contents of `:messages`:

```
:messages
Messages maintainer: Bram Moolenaar <Bram@vim.org>
Installing govim and gopls
Error detected while processing function <SNR>45_govimExit:
line   10:
E605: Exception not caught: govim plugin died :(
```

**Comment by myitcv** [comment]
@leighmcculloch just to confirm, you do have `go` on your PATH? i.e. it's not a wrapper like `go1.12.7` (got via https://github.com/golang/dl)?

**Comment by leighmcculloch** [comment]
I do have `go` in my path. I do have aliases defined for other versions of go in the form `go1.12.7` because I have a few versions of go installed, but the latest is also just in my `PATH` as `go`.

**Comment by myitcv** [comment]
Let's continue this conversation in #164 - we at least have some details from the log now.
