### ISSUE TITLE
cmd/govim: error when saving a go file

### ISSUE THREAD

**Issue by varun06** [myitcv/govim#224]
### What version of Vim/Gvim are you using?

<details><summary>Vim/Gvim version</summary><br><pre>
$ vim --version
8.1
</pre></details>

### What version of Go are you using (`go version`)?

<pre>
$ go version
go1.12.5
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
mac, amd64
</pre></details>

### What version/commit of `govim` are you using?
master

### What is the output of `:messages` in Vim?
Vim channel logfile: /var/folders/jn/803dcg5976z37rtnb5lvqc9h6n00dn/T//vim_channel_log_20190508_1522_13_np13VFhZzBb7
govim logfile: /var/folders/jn/803dcg5976z37rtnb5lvqc9h6n00dn/T/govim_20190508_1522_13.743731000_676704289

### Do the Vim channel or `govim` log files show anything interesting?
Nothing I can tell in a cursory look

### How did you install `govim`?

Vim 8 packages

### What did you do?
Save a file

### What did you expect to see?
File is saved

### What did you see instead?

an error message
<img width="1670" alt="Screen Shot 2019-05-08 at 2 46 34 PM" src="https://user-images.githubusercontent.com/1284070/57406030-73ed8800-71a5-11e9-8352-941c192dc647.png">

**Comment by myitcv** [comment]
Thanks @varun06: 

* can you give a bit more context here? For example, was this the first file in a new package? A `main` package? etc
* can you specify the commit of `govim` that you were using (`master` is a branch, which means the commit to which it is pointing changes over time)

My guess at this stage is that you're running into https://github.com/myitcv/govim/issues/86 (which is being tracked in https://github.com/golang/go/issues/31522)

**Comment by varun06** [comment]
yeah, it's a new go file in package. So looks like that I am hitting 86 for sure.

**Comment by myitcv** [comment]
Ok thanks. I think I'll close this in favour of #86. We can always re-open if it subsequently transpires there's another issue.
