### ISSUE TITLE
cmd/govim: quickfix not consistently populated at load time

### ISSUE THREAD

**Issue by leitzler** [myitcv/govim#255]
### What version of Vim/Gvim are you using?
<details><summary>Vim/Gvim version</summary><br><pre>
$ vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled May 26 2019 08:44:50)
Included patches: 1-1397
Compiled by leitzler@leitzlerdev.europe-north1-a.c.devdomain.internal
Huge version without GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     -tag_old_static
+arabic            -farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    -tcl
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    -gettext           +netbeans_intg     +textprop
+byte_offset       -hangul_input      +num64             +timers
+channel           +iconv             +packages          +title
+cindent           +insert_expand     +path_extra        -toolbar
-clientserver      +job               -perl              +user_commands
-clipboard         +jumplist          +persistent_undo   +vartabs
+cmdline_compl     +keymap            +postscript        +vertsplit
+cmdline_hist      +lambda            +printer           +virtualedit
+cmdline_info      +langmap           +profile           +visual
+comments          +libcall           -python            +visualextra
+conceal           +linebreak         -python3           +viminfo
+cryptv            +lispindent        +quickfix          +vreplace
+cscope            +listcmds          +reltime           +wildignore
+cursorbind        +localmap          +rightleft         +wildmenu
+cursorshape       -lua               -ruby              +windows
+dialog_con        +menu              +scrollbind        +writebackup
+diff              +mksession         +signs             -X11
+digraphs          +modify_fname      +smartindent       -xfontset
-dnd               +mouse             +startuptime       -xim
-ebcdic            -mouseshape        +statusline        -xpm
+emacs_tags        +mouse_dec         -sun_workshop      -xsmp
+eval              -mouse_gpm         +syntax            -xterm_clipboard
+ex_extra          -mouse_jsbterm     +tag_binary        -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -O2 -fno-strength-reduce -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1                                        
Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -ldl                                                 
</pre></details>

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.4 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/leitzler/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/leitzler/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/tmp/tmp.j4itXIblg8/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build032108683=/tmp/go-build -gno-record-gcc-switches"  
</pre></details>

### What version/commit of `govim` are you using?
Latest@master (6f9facacfbfd7e09c1df27d6ee5be4a0237cea46)

### What is the output of `:messages` in Vim?
<pre>
Messages maintainer: Bram Moolenaar <Bram@vim.org>                                                                                                               
Vim channel logfile: /tmp/vim_channel_log_20190529_2055_30_OutuexxhYRQ8                                                                                          
"main.go" 5L, 35C                                                                                                                                                
govim logfile: /tmp/govim_20190529_2055_30.850569291_335058429                                                                                                   
"main.go" 5L, 35C written    
</pre>

### Do the Vim channel or `govim` log files show anything interesting?
https://gist.github.com/leitzler/b741a60fed9d840f55b60d6b69d0f222

### How did you install `govim`?

Vim-plug

### What did you do?

```
$ go mod init x
go: creating new go.mod: module x
$ cat > main.go <<EOF
> package main
>
> func main() {
>       asd
> }
> EOF
$
```

Then open the file `vi main.go`, and immediately write it `:w`, and then tried to open the Quickfix `:cw`.

### What did you expect to see?
Syntax error on the `asd`-line

### What did you see instead?
No errors. Note that this is a pretty slow machine, and if I wait for a few seconds between the commands it actually works.

**Comment by myitcv** [comment]
@leitzler - thanks again for reporting the issue and the repro. See #261 - the current implementation of quickfix population was just plain wrong. The current implementation being so wrong was the reason that #136 couldn't be merged... and because I don't use the quickfix window I'm sad to say I didn't prioritise this. Thanks for forcing me to rectify all of those points!
