### ISSUE TITLE
cmd/govim: add command to run string/[]byte functions on ranges

### ISSUE THREAD

**Issue by mvdan** [myitcv/govim#273]
For example, I use go-fuzz, and sometimes the crash inputs contain non-printable characters. I then want to add those bytes as a double-quoted Go string literal in a test case.

However, there's no trivial way to do that. One option is to write a small `filequote.go` program, that takes stdin and quotes it via strconv.Quote. @myitcv suggested that govim could do this instead, which is a great idea.

The plugin could also offer unquote, so that one can quote and unquote specific ranges/selections.

I might have a look at this next week.

**Comment by myitcv** [comment]
Sounds great. I'd suggest making this a [range-based command](https://vimhelp.org/usr_40.txt.html#40.2). Take a look [here](https://github.com/myitcv/govim/blob/6d1ebbf7e4c5f7cb244656ce1e76a017b34ea010/cmd/govim/main.go#L167) for where the bulk of functions/commands are defined.

The only tricky part with this will be also making this work for visual selections, where I think you need to use marks to find the start/end of the visual selection:

https://vi.stackexchange.com/questions/11025/passing-visual-range-to-a-command-as-its-argument

**Comment by mvdan** [comment]
Another thought - this should also support `strconv.QuoteToASCII`.

**Comment by myitcv** [comment]
I had a random thought on this last night. Perhaps the functionality could/should be generalised to be able to call any function in the standard library of the form:

```
func(string) string
func(string) (string, error)
func([]byte) []byte
func([]byte) ([]byte, error)
```

We could then have completion support (e.g. via `<Tab>`) whilst typing the command:

```
:GOVIMStringFunc strconv.Quote
```

These commands would default to using a range argument implicitly, unless passed a string explicitly.

**Comment by mvdan** [comment]
I really like that idea :) Then my point about `QuoteToASCII` doesn't need any special attention.

**Comment by myitcv** [comment]
Dare I suggest, we could even use `gogrep` as part of a code generation step creates a map from the string `"$pkgpath.$function"` to the string function (one of the signatures above)?
