### ISSUE TITLE
feedback: better model for syntax errors

### ISSUE THREAD

**Issue by myitcv** [myitcv/govim#274]
I'd like to request some feedback on how best to handle syntax errors in Go files.

### Current state

At the moment, a syntax error in a Go file _prevents_ the file from being saved (assuming `"FormatOnSave"` is set to something other than `""`), because the corresponding `gopls` method will return an error. This seems less than ideal, because it forces the user to `:noautocmd w`

### Option 1: echo error message, allow save

The alternative is to allow the save, and echo the error message. But that error message quick and easily gets lost. Also not ideal.

### Option 2: allow save, rely on user spotting issue in quickfix window

The syntax error _is_ reported via the quickfix window diagnostics, so maybe this is sufficient? i.e. we just swallow the error from the user's perspective, and simply use it as an indication "do not try to apply any edits". Requires that a user does _not_ have `"QuickfixAutoDiagnosticsDisable"` set to a non-zero value (or that they call `GOVIMQuickfixDiagnostics` as and when required)

### Option 3: allow save, open quickfix window if there are entries

Building on option 2, we could auto-open the quickfix window if there are entries (and close it when there are none, effectively the `:cw` command in Vim)

Thoughts?

cc @leitzler who raised this on Slack.

**Comment by myitcv** [comment]
(important edit made to quickfix point)

**Comment by myitcv** [comment]
(edit to make options clearer; add option on auto-opening quickfix window)

**Comment by leitzler** [comment]
I think option 3 would be ideal for how I use vim, but I guess option 3 doesn't have to rule out option 2 right? If it is possible to configure wether to auto open quickfix or not.

Can you add a bit more context to:
> "do not try to apply any edits"

It is fairly common (for me) to save and then almost immediately go to insert mode and start to edit the file again. I assume that could be a problem since updates are sent on each keystroke, right?

**Comment by myitcv** [comment]
Thanks @leitzler 

> I think option 3 would be ideal for how I use vim

I think this option almost certainly applies to how the majority use Vim, hence it's my current preference. 

> but I guess option 3 doesn't have to rule out option 2 right? If it is possible to configure wether to auto open quickfix or not.

Correct, except I would like to avoid creating an option soup. 

To avoid the option soup, I might just provide further config options that allow the user to provide callbacks for specific events to override the default behaviour. This situation would be one example of where a config option callback would naturally be provided.

> Can you add a bit more context to:
>
>> "do not try to apply any edits"

Apologies, this is probably confusing. It's also somewhat nonsensical. All I meant by this is that when a `gopls` method returns, in a non-error situation there might be edits to apply to the buffer in order to correctly format it. If however we receive an error, we should not apply the edits. Indeed it's almost certainly the case that we would not receive any edits if we do receive an error. 

So this is a comment more from `govim`'s perspective, not the user's.

**Comment by myitcv** [comment]
Ok, for now I'll go with option 2: #276 

However I've raised #277 for the implementation of option 3.

I've also [added a tip](https://github.com/myitcv/govim/wiki/vimrc-tips#-tip-mapping-to-open-quickfix-window-without-shifting-focus) on how to define a useful mapping for opening the quickfix window for now.
