### ISSUE TITLE
cmd/govim: syntax errors dominate package diagnostics

### ISSUE THREAD

**Issue by leitzler** [myitcv/govim#297]
### What version of Vim/Gvim are you using?

<details><summary>Vim/Gvim version</summary><br><pre>
$ vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled May 26 2019 08:44:50)
Included patches: 1-1397
Compiled by leitzler@leitzlerdev.europe-north1-a.c.devdomain.internal
Huge version without GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     -tag_old_static
+arabic            -farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    -tcl
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    -gettext           +netbeans_intg     +textprop
+byte_offset       -hangul_input      +num64             +timers
+channel           +iconv             +packages          +title
+cindent           +insert_expand     +path_extra        -toolbar
-clientserver      +job               -perl              +user_commands
-clipboard         +jumplist          +persistent_undo   +vartabs
+cmdline_compl     +keymap            +postscript        +vertsplit
+cmdline_hist      +lambda            +printer           +virtualedit
+cmdline_info      +langmap           +profile           +visual
+comments          +libcall           -python            +visualextra
+conceal           +linebreak         -python3           +viminfo
+cryptv            +lispindent        +quickfix          +vreplace
+cscope            +listcmds          +reltime           +wildignore
+cursorbind        +localmap          +rightleft         +wildmenu
+cursorshape       -lua               -ruby              +windows
+dialog_con        +menu              +scrollbind        +writebackup
+diff              +mksession         +signs             -X11
+digraphs          +modify_fname      +smartindent       -xfontset
-dnd               +mouse             +startuptime       -xim
-ebcdic            -mouseshape        +statusline        -xpm
+emacs_tags        +mouse_dec         -sun_workshop      -xsmp
+eval              -mouse_gpm         +syntax            -xterm_clipboard
+ex_extra          -mouse_jsbterm     +tag_binary        -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -O2 -fno-strength-reduce -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1                                        
Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -ldl            
</pre></details>

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.4 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/leitzler/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/leitzler/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/tmp/tmp.p2eLvfk4gh/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build777462759=/tmp/go-build -gno-record-gcc-switches"      
</pre></details>

### What version/commit of `govim` are you using?
Current master (c14a323551a641734eaef3c70cee9bd21e862d18)

### What is the output of `:messages` in Vim?
Log file names only

### Do the Vim channel or `govim` log files show anything interesting?
Not really

### How did you install `govim`?

vim-plug

### What did you do?

```
$ cd $(mktemp -d) && go mod init foo
$ cat > main.go <<EOF
> package main
>
> func main() {
> foo
> }
> EOF
$ cat > a.go <<EOF
> package main
>
> bar
> EOF
$ vi main.go a.go
2 files to edit
```

### What did you expect to see?
`main.go` open and quickfix populated with the the incorrect line in `main.go` ("main.go line 4 - foo").

And, if I understand how quickfix is supposed to work (as opposite to the location list), I also expect that the quickfix list is populated with items from all open buffers.

### What did you see instead?
`main.go` open and quickfix populated with the incorrect item in `a.go` ("a.go line 3 - bar")

**Comment by myitcv** [comment]
This is because the error in `a.go` is a syntax error. Hence `gopls` bails out before detecting the type-checking error in `main.go` (indeed the package more broadly).

So I think `gopls` (and hence `govim`) is doing the right thing here. Unless, and it could be argued along these  lines, you think `gopls` should ignore `a.go` and try and type-check the rest of the package?

> I also expect that the quickfix list is populated with items from all open buffers.

This is correct, but as explained above, the syntax error prevents the type-checking phase from evening happening.

**Comment by leitzler** [comment]
Obviously, those syntax errors keeps biting me.. Closing this as any change should be in `gopls`, sorry for the disturbance.

**Comment by myitcv** [comment]
I'd be quite happy if you wanted to leave this issue open here, and then open a `gopls` issue to discuss?

**Comment by leitzler** [comment]
Works as expected now that https://github.com/golang/go/issues/32596 is solved, closing!
