### ISSUE TITLE
ci: fix flaky tests in signs & quickfix_config test cases

### ISSUE THREAD

**Issue by leitzler** [myitcv/govim#408]
### What version/commit of `govim` are you using?
Latest master, https://github.com/myitcv/govim/commit/54b65c8c61dc92ac9eea331d9d9a077784a56463

### What did you do?
I've noticed that test scripts that involves calls to vim's `sign_getplaced(...)` is flaky.

The reason is that `PublishDiagnostics callback` is sometimes used to determine when the signs are updated, e.g. from `cmd/govim/testdata/signs.txt`:
<pre>
# Fixing the last quickfix entry should remove the last sign
vim call append '[5, "\tvar v string"]'
[vim] [!vim:v8.1.1711] vim ex 'doautocmd TextChangedI' # make sure gopls is notified if incremental buffer updates isn't supported
errlogmatch -wait 30s 'PublishDiagnostics callback: &protocol.PublishDiagnosticsParams{\n\S+:\s+URI:\s+"file://'$WORK/main.go
vim -indent expr 'sign_getplaced(\"main.go\", {\"group\": \"*\"})'
! stderr .+
cmp stdout placed_nosign.golden
</pre>

Since `PublishDiagnostics callback` is parsed to quickfix entries and then signs, there is a time window where the quickfix and signs aren't updated yet. If `sign_getplaced(...)` is called too quickly, it might return the signs that is about to be removed.

Those tests must rely on something other than `PublishDiagnostics callback` that happens after quickfix is done updating.

**Comment by myitcv** [comment]
Thanks for raising this (along with all the others!) - incredibly useful to have issues to track and discuss things.

Totally agree with your analysis. Indeed I think this sort of timing related thing is likely the cause of flakes described in #403 

Hence I've pushed up https://github.com/myitcv/govim/pull/410 to try and deal with the format-related flakes. You'll notice that I'm instead waiting on a log line of `govim` executing a command/function in Vim. This might seem a bit tied to the detail, but I can't see a better way (for now). 

Might be worth considering something similar for the sign-related flakes?

**Comment by myitcv** [comment]
There is a full build log for the quickfix_config flake in #420

**Comment by leitzler** [comment]
Pending #435

**Comment by leitzler** [comment]
Should be fixed as #436 is merged now
