### ISSUE TITLE
cmd/govim: consider placing hover popup botleft instead of topleft

### ISSUE THREAD

**Issue by myitcv** [myitcv/govim#421]
As observed by @cespare, the type (signature) in a hover popup appears at the bottom of the popup window. 

Placing the hover popup topleft (i.e. it appears below and to the right of the mouse/cursor) therefore means this information is furthest away from the identifier we are hovering over. 

Should we, therefore, place the popup botleft (i.e. above and to the right of the mouse/cursor)? 

Thoughts, please.

**Comment by myitcv** [comment]
> That might require tweaking the text we get back from gopls.

Indeed. I'd be minded to avoid that. 

`gopls` can be configured to return one of three "brevity levels" of documentation:

* None
* Synopsis
* Full

All of them put the type (signature) after the docs. I think this points to us changing to a `botleft` placement.

**Comment by cespare** [comment]
To me, having the popup above seems surprising. I'd prefer it to be below.

What do the other editors do?

What's the problem with altering the gopls output? Isn't it a trivial change to move the bottom line to the top (and delete the blank line), or are there cases where it's more complicated than that?

**Comment by myitcv** [comment]
VSCode shows it above-and-to-the right, hence why (I suspect) they have gone for this ordering.

> What's the problem with altering the gopls output? 

No problem, but I would instead ask them to put this behind config; makes it more robust.

I'll create an issue there to discuss. FWIW, I also think below-and-to-the-right is better.

**Comment by myitcv** [comment]
Actually, there is a good reason to put the popup above-and-to-the-right; when you attempting completion (where the candidates appear below-and-to-the-right) the associated docs could then appear above-and-to-the-right. Having hover popups appear above-and-to-the-right would then be consistent. Thoughts?

**Comment by cespare** [comment]
So we would show two popup windows at the same time? Is that how things work in other editors/IDEs? Seems kind of busy. I don't think I'd want the doc popup when I'm autocompleting, though perhaps I'd change my mind if I tried it.

**Comment by myitcv** [comment]
> So we would show two popup windows at the same time? Is that how things work in other editors/IDEs? Seems kind of busy

I think there are various options of what to show. But I also think I got myself in a muddle above.

What I _meant_ to say was that the _signature_ information is shown once a candidate in the completion list is chosen. When an option is chosen, the candidate list (shown below-and-to-the-right) disappears and the signature help (shown above-and-to-the-right) appears. Whether documentation is shown I'm not 100% sure, but I think it's an option as you are moving the cursor through the candidate list, and if turned on this popup appears to the right of the candidate list

**Comment by myitcv** [comment]
This was fixed in #431, i.e. hover popups are placed above-and-to-the-right of the cursor.

#392 captures us using the preview popup to show completion candidate docs as we cycle through the list.
