### ISSUE TITLE
cmd/govim: autoindent and curly brace issues

### ISSUE THREAD

**Issue by ChristianLindLarsen** [myitcv/govim#430]
I'm not certain if this is a Vim or Govim issue - I'm new to both, so apologies if this shouldn't be an issue created here. 

### What version of Vim/Gvim are you using?

$ vim --version
`VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 27 2019 00:46:03)`

### What version of Go are you using (`go version`)?

`go version go1.12 darwin/amd64`

### What operating system and processor architecture are you using (`go env`)?
```
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
```

### What did you do?

When creating, say, a for loop, I'd like for vim/govim to behave similarly to an IDE. Currently, I have the following situation( "|" represents cursor)

```
// Some other code, the following is nested..
            for _, something := range slice {
|
```

1.) The corresponding `}` curly brace isn't automatically created.
2.) When pressing `enter` for newline, the cursor will be kicked all the way back on the next line - rather than indenting properly compared to the nesting level

### What did you expect to see?

```
// Some other code, the following is nested..
            for _, something := range slice { | // I press enter here
```

Then, upon pressing enter

```
// Some other code, the following is nested..
            for _, something := range slice {
                 | // Curly brace is set automatically at correct nesting level and cursor is bumped in by a tab
            }
```

Again apologies if this is "just" a vim setting I'm not aware of. Obviously I'd like to be pointed towards the correct approach to solve it either way :-) 

Edit: Oddly, upon creating a new function, this works completely as intended. But I do not find it as working inside functions, f.e. nested for loops and so on.

**Comment by myitcv** [comment]
Thanks for raising this @ChristianLindLarsen - your question I think points to the fact we need to do more work for newcomers to Vim, newcomers to `govim` etc. 

Regarding auto-indent: this is a Vim feature; I've just raised https://github.com/myitcv/govim/pull/432 to suggest settings that should be part of a user's out-of-the-box `.vimrc`

Regarding auto-brace insertion: this is not currently a core part of Vim, nor is it something we do in `govim`. I use https://github.com/jiangmiao/auto-pairs. In the future we might look at distributing this with `govim` for a good out-of-the-box default experience.

**Comment by myitcv** [comment]
Also just added https://github.com/myitcv/govim/wiki/vimrc-tips#-tip-auto-insert-closing-parentheses-braces-quotes-etc
