### ISSUE TITLE
cmd/govim: unclear how to trigger code completion

### ISSUE THREAD

**Issue by ReK2Fernandez** [myitcv/govim#483]
Hello feel free to close this is a small question I can't find anyplace on this wiki:
I just installed this and removed go-vim so far everything I need works but code completion,
the question here is that Is not clear:
- if I need to add "another" plungin for this to work or it will work with clean vim out of the box with this plugin.
- what is the keystrokes to get the bubble info with out hovering the mouse, I try to avoid using the mouse as much as I can.

Thanks and sorry again for so simple questions... maybe we can add it to the wiki.

**Comment by myitcv** [comment]
Hi @ReK2Fernandez - thanks for raising the issue. I think your question highlights that we haven't got good enough documentation 😄 

To that end, I've ensured I answer both of your questions in the wiki that is there to explain "What can `govim` do, and how do I do it?"

https://github.com/myitcv/govim/wiki/govim-plugin-API

Perhaps you could give that a read through and see whether you feel your questions are now answered? 

If so, great. It not, I'd appreciate you pointing out where things could be further clarified.

Thanks

**Comment by ReK2Fernandez** [comment]
@myitcv this is perfect thank you! ctrl+x, ctrl+o works! Any recommendation for a plugin that works well with govim for auto completion if I decide to ever go that route?

**Comment by myitcv** [comment]
Great. Sounds like we can close this specific issue for now, but please shout if that's an incorrect assumption, and/or open a new issue with anything new.

> Any recommendation for a plugin that works well with govim for auto completion if I decide to ever go that route?

I don't, but if you find a good answer, please let us know and we can add a tip on that specific question!

(If you are in the [Gophers Slack](https://invite.slack.golangbridge.org), the `#vim` channel might have some suggestions)
