### ISSUE TITLE
cmd/govim: gopls crashes when writing a simple file

### ISSUE THREAD

**Issue by myitcv** [myitcv/govim#98]
Start with a simple file:

```
package main
```

Then type to get yourself to this position:

```
package main

import "fmt"

func m
```

You will notice `govim` crashes just as you add a `<space>` after `func`.

<details><summary>Log output</summary><br><pre>
gopls.Initialize() call; params:
&protocol.InitializeParams{
    InnerInitializeParams: protocol.InnerInitializeParams{
        ProcessID:             0,
        RootPath:              "",
        RootURI:               "file:///home/myitcv/gostuff/src/github.com/myitcv/playground",
        Capabilities:          {},
        InitializationOptions: nil,
        Trace:                 "",
    },
    WorkspaceFoldersInitializeParams: protocol.WorkspaceFoldersInitializeParams{},
}
gopls.Initialize() return; err: <nil>; res:
&protocol.InitializeResult{
    Capabilities: protocol.ServerCapabilities{
        InnerServerCapabilities: protocol.InnerServerCapabilities{
            TextDocumentSync: map[string]interface {}{
                "change":    float64(1),
                "openClose": bool(true),
            },
            HoverProvider:      true,
            CompletionProvider: &protocol.CompletionOptions{
                TriggerCharacters:   {"."},
                AllCommitCharacters: nil,
                ResolveProvider:     false,
            },
            SignatureHelpProvider: &protocol.SignatureHelpOptions{
                TriggerCharacters: {"(", ","},
            },
            DefinitionProvider:               true,
            ReferencesProvider:               false,
            DocumentHighlightProvider:        true,
            DocumentSymbolProvider:           true,
            WorkspaceSymbolProvider:          false,
            CodeActionProvider:               true,
            CodeLensProvider:                 (*protocol.CodeLensOptions)(nil),
            DocumentFormattingProvider:       true,
            DocumentRangeFormattingProvider:  true,
            DocumentOnTypeFormattingProvider: (*struct { FirstTriggerCharacter string "json:\"firstTriggerCharacter\""; MoreTriggerCharacter []string "json:\"moreTriggerCharacter,omitempty\"" })(nil),
            RenameProvider:                   false,
            DocumentLinkProvider:             (*protocol.DocumentLinkOptions)(nil),
            ExecuteCommandProvider:           (*protocol.ExecuteCommandOptions)(nil),
            Experimental:                     nil,
        },
        ImplementationServerCapabilities:   protocol.ImplementationServerCapabilities{},
        TypeDefinitionServerCapabilities:   protocol.TypeDefinitionServerCapabilities{TypeDefinitionProvider:true},
        WorkspaceFoldersServerCapabilities: protocol.WorkspaceFoldersServerCapabilities{},
        ColorServerCapabilities:            protocol.ColorServerCapabilities{},
        FoldingRangeServerCapabilities:     protocol.FoldingRangeServerCapabilities{},
        DeclarationServerCapabilities:      protocol.DeclarationServerCapabilities{},
        SelectionRangeServerCapabilities:   protocol.SelectionRangeServerCapabilities{},
    },
    Custom: {},
}
gopls.DidOpen() call; params:
&protocol.DidOpenTextDocumentParams{
    TextDocument: protocol.TextDocumentItem{URI:"file:///home/myitcv/gostuff/src/github.com/myitcv/playground/main.go", LanguageID:"", Version:0, Text:"package main"},
}
gopls.DidOpen() return; err: <nil>
gopls.DidChange() call; params:
&protocol.DidChangeTextDocumentParams{
    TextDocument: protocol.VersionedTextDocumentIdentifier{
        TextDocumentIdentifier: protocol.TextDocumentIdentifier{URI:"file:///home/myitcv/gostuff/src/github.com/myitcv/playground/main.go"},
        Version:                1,
    },
    ContentChanges: {
        {
            Range:       (*protocol.Range)(nil),
            RangeLength: 0,
            Text:        "package main\n",
        },
    },
}
gopls.DidChange() return; err: <nil>
gopls.DidChange() call; params:
&protocol.DidChangeTextDocumentParams{
    TextDocument: protocol.VersionedTextDocumentIdentifier{
        TextDocumentIdentifier: protocol.TextDocumentIdentifier{URI:"file:///home/myitcv/gostuff/src/github.com/myitcv/playground/main.go"},
        Version:                2,
    },
    ContentChanges: {
        {
            Range:       (*protocol.Range)(nil),
            RangeLength: 0,
            Text:        "package main\n\n",
        },
    },
}
gopls.DidChange() return; err: <nil>
gopls.DidChange() call; params:
&protocol.DidChangeTextDocumentParams{
    TextDocument: protocol.VersionedTextDocumentIdentifier{
        TextDocumentIdentifier: protocol.TextDocumentIdentifier{URI:"file:///home/myitcv/gostuff/src/github.com/myitcv/playground/main.go"},
        Version:                3,
    },
    ContentChanges: {
        {
            Range:       (*protocol.Range)(nil),
            RangeLength: 0,
            Text:        "package main\n\ni",
        },
    },
}
gopls.DidChange() return; err: <nil>
gopls.DidChange() call; params:
&protocol.DidChangeTextDocumentParams{
    TextDocument: protocol.VersionedTextDocumentIdentifier{
        TextDocumentIdentifier: protocol.TextDocumentIdentifier{URI:"file:///home/myitcv/gostuff/src/github.com/myitcv/playground/main.go"},
        Version:                4,
    },
    ContentChanges: {
        {
            Range:       (*protocol.Range)(nil),
            RangeLength: 0,
            Text:        "package main\n\nim",
        },
    },
}
gopls.DidChange() return; err: <nil>
gopls.DidChange() call; params:
&protocol.DidChangeTextDocumentParams{
    TextDocument: protocol.VersionedTextDocumentIdentifier{
        TextDocumentIdentifier: protocol.TextDocumentIdentifier{URI:"file:///home/myitcv/gostuff/src/github.com/myitcv/playground/main.go"},
        Version:                5,
    },
    ContentChanges: {
        {
            Range:       (*protocol.Range)(nil),
            RangeLength: 0,
            Text:        "package main\n\nimp",
        },
    },
}
gopls.DidChange() return; err: <nil>
gopls.DidChange() call; params:
&protocol.DidChangeTextDocumentParams{
    TextDocument: protocol.VersionedTextDocumentIdentifier{
        TextDocumentIdentifier: protocol.TextDocumentIdentifier{URI:"file:///home/myitcv/gostuff/src/github.com/myitcv/playground/main.go"},
        Version:                6,
    },
    ContentChanges: {
        {
            Range:       (*protocol.Range)(nil),
            RangeLength: 0,
            Text:        "package main\n\nimpo",
        },
    },
}
gopls.DidChange() return; err: <nil>
gopls.DidChange() call; params:
&protocol.DidChangeTextDocumentParams{
    TextDocument: protocol.VersionedTextDocumentIdentifier{
        TextDocumentIdentifier: protocol.TextDocumentIdentifier{URI:"file:///home/myitcv/gostuff/src/github.com/myitcv/playground/main.go"},
        Version:                7,
    },
    ContentChanges: {
        {
            Range:       (*protocol.Range)(nil),
            RangeLength: 0,
            Text:        "package main\n\nimpor",
        },
    },
}
gopls.DidChange() return; err: <nil>
gopls.DidChange() call; params:
&protocol.DidChangeTextDocumentParams{
    TextDocument: protocol.VersionedTextDocumentIdentifier{
        TextDocumentIdentifier: protocol.TextDocumentIdentifier{URI:"file:///home/myitcv/gostuff/src/github.com/myitcv/playground/main.go"},
        Version:                8,
    },
    ContentChanges: {
        {
            Range:       (*protocol.Range)(nil),
            RangeLength: 0,
            Text:        "package main\n\nimport",
        },
    },
}
gopls.DidChange() return; err: <nil>
gopls.DidChange() call; params:
&protocol.DidChangeTextDocumentParams{
    TextDocument: protocol.VersionedTextDocumentIdentifier{
        TextDocumentIdentifier: protocol.TextDocumentIdentifier{URI:"file:///home/myitcv/gostuff/src/github.com/myitcv/playground/main.go"},
        Version:                9,
    },
    ContentChanges: {
        {
            Range:       (*protocol.Range)(nil),
            RangeLength: 0,
            Text:        "package main\n\nimport ",
        },
    },
}
gopls.DidChange() return; err: <nil>
gopls.DidChange() call; params:
&protocol.DidChangeTextDocumentParams{
    TextDocument: protocol.VersionedTextDocumentIdentifier{
        TextDocumentIdentifier: protocol.TextDocumentIdentifier{URI:"file:///home/myitcv/gostuff/src/github.com/myitcv/playground/main.go"},
        Version:                10,
    },
    ContentChanges: {
        {
            Range:       (*protocol.Range)(nil),
            RangeLength: 0,
            Text:        "package main\n\nimport \"\"",
        },
    },
}
gopls.DidChange() return; err: <nil>
gopls.DidChange() call; params:
&protocol.DidChangeTextDocumentParams{
    TextDocument: protocol.VersionedTextDocumentIdentifier{
        TextDocumentIdentifier: protocol.TextDocumentIdentifier{URI:"file:///home/myitcv/gostuff/src/github.com/myitcv/playground/main.go"},
        Version:                11,
    },
    ContentChanges: {
        {
            Range:       (*protocol.Range)(nil),
            RangeLength: 0,
            Text:        "package main\n\nimport \"f\"",
        },
    },
}
gopls.DidChange() return; err: <nil>
gopls.DidChange() call; params:
&protocol.DidChangeTextDocumentParams{
    TextDocument: protocol.VersionedTextDocumentIdentifier{
        TextDocumentIdentifier: protocol.TextDocumentIdentifier{URI:"file:///home/myitcv/gostuff/src/github.com/myitcv/playground/main.go"},
        Version:                12,
    },
    ContentChanges: {
        {
            Range:       (*protocol.Range)(nil),
            RangeLength: 0,
            Text:        "package main\n\nimport \"fm\"",
        },
    },
}
gopls.DidChange() return; err: <nil>
gopls.DidChange() call; params:
&protocol.DidChangeTextDocumentParams{
    TextDocument: protocol.VersionedTextDocumentIdentifier{
        TextDocumentIdentifier: protocol.TextDocumentIdentifier{URI:"file:///home/myitcv/gostuff/src/github.com/myitcv/playground/main.go"},
        Version:                13,
    },
    ContentChanges: {
        {
            Range:       (*protocol.Range)(nil),
            RangeLength: 0,
            Text:        "package main\n\nimport \"fmt\"",
        },
    },
}
gopls.DidChange() return; err: <nil>
gopls.DidChange() call; params:
&protocol.DidChangeTextDocumentParams{
    TextDocument: protocol.VersionedTextDocumentIdentifier{
        TextDocumentIdentifier: protocol.TextDocumentIdentifier{URI:"file:///home/myitcv/gostuff/src/github.com/myitcv/playground/main.go"},
        Version:                14,
    },
    ContentChanges: {
        {
            Range:       (*protocol.Range)(nil),
            RangeLength: 0,
            Text:        "package main\n\nimport \"fmt\"\n",
        },
    },
}
gopls.DidChange() return; err: <nil>
gopls.DidChange() call; params:
&protocol.DidChangeTextDocumentParams{
    TextDocument: protocol.VersionedTextDocumentIdentifier{
        TextDocumentIdentifier: protocol.TextDocumentIdentifier{URI:"file:///home/myitcv/gostuff/src/github.com/myitcv/playground/main.go"},
        Version:                15,
    },
    ContentChanges: {
        {
            Range:       (*protocol.Range)(nil),
            RangeLength: 0,
            Text:        "package main\n\nimport \"fmt\"\n\n",
        },
    },
}
gopls.DidChange() return; err: <nil>
gopls.DidChange() call; params:
&protocol.DidChangeTextDocumentParams{
    TextDocument: protocol.VersionedTextDocumentIdentifier{
        TextDocumentIdentifier: protocol.TextDocumentIdentifier{URI:"file:///home/myitcv/gostuff/src/github.com/myitcv/playground/main.go"},
        Version:                16,
    },
    ContentChanges: {
        {
            Range:       (*protocol.Range)(nil),
            RangeLength: 0,
            Text:        "package main\n\nimport \"fmt\"\n\nf",
        },
    },
}
gopls.DidChange() return; err: <nil>
gopls.DidChange() call; params:
&protocol.DidChangeTextDocumentParams{
    TextDocument: protocol.VersionedTextDocumentIdentifier{
        TextDocumentIdentifier: protocol.TextDocumentIdentifier{URI:"file:///home/myitcv/gostuff/src/github.com/myitcv/playground/main.go"},
        Version:                17,
    },
    ContentChanges: {
        {
            Range:       (*protocol.Range)(nil),
            RangeLength: 0,
            Text:        "package main\n\nimport \"fmt\"\n\nfu",
        },
    },
}
gopls.DidChange() return; err: <nil>
gopls.DidChange() call; params:
&protocol.DidChangeTextDocumentParams{
    TextDocument: protocol.VersionedTextDocumentIdentifier{
        TextDocumentIdentifier: protocol.TextDocumentIdentifier{URI:"file:///home/myitcv/gostuff/src/github.com/myitcv/playground/main.go"},
        Version:                18,
    },
    ContentChanges: {
        {
            Range:       (*protocol.Range)(nil),
            RangeLength: 0,
            Text:        "package main\n\nimport \"fmt\"\n\nfun",
        },
    },
}
gopls.DidChange() return; err: <nil>
gopls.DidChange() call; params:
&protocol.DidChangeTextDocumentParams{
    TextDocument: protocol.VersionedTextDocumentIdentifier{
        TextDocumentIdentifier: protocol.TextDocumentIdentifier{URI:"file:///home/myitcv/gostuff/src/github.com/myitcv/playground/main.go"},
        Version:                19,
    },
    ContentChanges: {
        {
            Range:       (*protocol.Range)(nil),
            RangeLength: 0,
            Text:        "package main\n\nimport \"fmt\"\n\nfunc",
        },
    },
}
gopls.DidChange() return; err: <nil>

</pre></details>

Will raise once we have clarification on the expected behaviour of `gopls` with respect to files not persisted to disk.

**Comment by myitcv** [comment]
Raised as https://github.com/golang/go/issues/31341

**Comment by hmarr** [comment]
I also see `failed to resolve position: failed to translate char colum for buffer 1: FromUTF16Column: chr goes beyond the line` relatively frequently. Not sure if it's related.

<details>
<summary>Log output</summary>

```
2019-04-18T15:41:13.758878: vim start =======================
2019-04-18T15:41:13.758878: recvJSONMsg: [123] ["function","autocommand:3"]
2019-04-18T15:41:13.758878: vim end =======================
2019-04-18T15:41:13.758932: run: waiting to read a JSON message
2019-04-18T15:41:13.759149: vim start =======================
2019-04-18T15:41:13.759149: sendJSONMsg: [0,[82,"call","getcwd"]]
2019-04-18T15:41:13.759149: vim end =======================
2019-04-18T15:41:13.759341: vim start =======================
2019-04-18T15:41:13.759341: recvJSONMsg: [124] ["callback",82,["","/Users/.../some_file.go"]]
2019-04-18T15:41:13.759341: vim end =======================
2019-04-18T15:41:13.759362: run: waiting to read a JSON message
2019-04-18T15:41:13.759656: got error whilst handling autocommand:3: failed to resolve position: failed to translate char colum for buffer 1: FromUTF16Column: chr goes beyond the line
2019-04-18T15:41:13.759674: vim start =======================
2019-04-18T15:41:13.759674: sendJSONMsg: [123,["got error whilst handling autocommand:3: failed to resolve position: failed to translate char colum for buffer 1: FromUTF16Column: chr goes beyond the line",""]]
2019-04-18T15:41:13.759674: vim end =======================
```

</details>

**Comment by myitcv** [comment]
Thanks @hmarr - if you see this again, please can you include the full output from the log (assuming it's not sensitive; not file contents are included in this log files, for now)? Confirming the sequence of events here would be useful, particularly if you have a small repro.
